### ISSUE TITLE
ANR on android 14

### ISSUE THREAD

**Issue by cw-saurav** [iou90/react-native-autoheight-webview#266]
**Bug description:**

ANR on loading of webview which contains image  of App. This webview is present on first screen of app. 

Stack trace :
at J.N.MTXp4fn_(Native method)
       at WV.x6.onDraw(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:227)
       at com.android.webview.chromium.WebViewChromium.onDraw(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:40)
       at android.webkit.WebView.onDraw(WebView.java:2956)
       at android.view.View.draw(View.java:24728)
       at android.view.View.updateDisplayListIfDirty(View.java:23520)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
       at android.view.View.updateDisplayListIfDirty(View.java:23445)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)

**To Reproduce:**

**Source (static HTML or url):**
HTML

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: android 14
 - OS version: any
 - react-native version: 0.74
 - react-native-webview version: 13.8.1
 - react-native-autoheight-webview version: 1.6.5

**Comment by milan-canary** [comment]
I am also getting so many ANRs like this
